[package]
name = "rcedit-sys"
version = "0.1.0"
authors = ["Vladislav Nikonov <nikonov.vladislav@apriorit.com>"]
edition = "2018"
build = "build.rs"
links = "rcedit"

[build-dependencies]
cc = "1.0.56"